# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 */3 * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies # 下載所需的套件 (requirements.txt)
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run python main # 執行 main.py
      run: python main.py

    - name: Record time  # 時間紀錄
      run: echo `date` > date.log
    
    - name: Commit and push if changed   # 更新 readme.md
      run: |
        git diff
        git config --global user.email "tony20020507@gmail.com"
        git config --global user.name "tony11306"
        git add -A
        git commit -m "Updated Readme" || exit 
        git push
    
